version: 0.1
phases:
  install:
    commands:
      - zip lambda.zip index.py
      - aws cloudformation package --template ./serverless.yaml --s3-bucket maniaccounttest1 --region us-east-1 --output-template-file processedserverless.yaml
artifacts:
  type: zip
  files:
    - processedserverless.yaml
