AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample Lambda Safe Deployment Application
Resources:
  CodeDeployLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      AutoPublishAlias: live
      CodeUri: ./lambda.zip
      DeploymentPreference:
          Type: Linear10PercentEvery1Minute
